---
apiVersion: v1
kind: Secret
metadata:
  name: frontend1213-app-repo
  namespace: devhub
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-mad/frontend1213-app-gitops
